services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_DB=library
      - PGDATA=/var/lib/postgresql/data/library/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      sh -c "echo 'host all all all md5' >> /var/lib/postgresql/data/pg_hba.conf &&
             exec docker-entrypoint.sh postgres"
  backend:
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=library
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
