services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=127.0.0.1
      - DATABASE_PORT=5432
      - DATABASE_NAME=library
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=root